use_frameworks!

target 'NavigationBarManager_Example' do
  pod 'NavigationBarManager', :path => '../'

  target 'NavigationBarManager_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
